on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Install MCP servers with pipx
      run: |
        # Ensure pipx is installed
        python3 -m pip install --user pipx || exit 1
        
        # Verify pipx installation
        python3 -m pipx --version || exit 1
        
        # Configure pipx path
        python3 -m pipx ensurepath
